name: fluttercrew
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # STATE MANAGEMENT
  hooks_riverpod: ^2.1.3 # riverpod with hooks from Remi Rousselet
  flutter_hooks: ^0.18.5+1 # additional hooks' functionality

  # NETWORKING:
  dio: ^4.0.6 # http client

  # AUTOGEN:
  freezed: ^2.3.2 # generation for immutable classes that has a simple syntax/API
  build_runner: ^2.3.3 # generating files using Dart code
  json_serializable: ^6.6.1 # dart build system builders for handling JSON
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # ROUTER:
  go_router: ^6.0.6

  # CAROUSEL_SLIDER
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

